### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by ranocha** [SciML/SciMLStyle#21]
Just curious: Why 4 spaces indentation instead of 2? 

I'm basically asking because JuliaFormatter made some weird decisions, in particular for deeply nested code when trying (?) to keep the 92 characters length limit. I'm fine with the length limit, but think that some decisions would have been much better with a bit less indentation.

**Comment by ChrisRackauckas** [comment]
It's idiomatic Julia: https://docs.julialang.org/en/v1/manual/style-guide/#Indentation . I don't like 4 spaces, but 🤷

**Comment by ranocha** [comment]
I see, thanks
